name    'skysql-mdbe'
version '0.1.0'
source ''
author 'Massimo Siani'
license 'GPL, Version 2'
summary 'MariaDB Enterprise provisioning'
description 'A distribution-independent Provisioning mechanism for MariaDB-Manager.'
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/mysql', '>= 2.2.1'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'example42/stdmod', '>= 0.0.3'
