name    'skysql-mdbe'
version '0.1.0'
source 'https://github.com/massimosiani/MariaDB-Manager-provisioning'
author 'Massimo Siani'
license 'GNU General Public License, Version 2.0'
summary 'MariaDB Enterprise provisioning'
description 'A distribution-independent Provisioning mechanism for MariaDB-Manager.'
project_page 'https://github.com/massimosiani/MariaDB-Manager-provisioning'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/mysql', '>= 2.2.1'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'example42/stdmod', '>= 0.0.3'
